-- Microfixd / Microfyxd OS Complete Supabase Schema
-- Run this entire script in your Supabase SQL Editor:
-- Dashboard -> SQL Editor -> New query -> Paste & Run

-- 1. Enable pgvector for semantic vector embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- ── UI STATE STORE (Single Source of Truth) ──────────────────────────────
CREATE TABLE IF NOT EXISTS public.ui_state (
  id               TEXT PRIMARY KEY DEFAULT 'current',
  active_subsystem TEXT NOT NULL DEFAULT 'ai_core',
  active_room      TEXT DEFAULT 'ai_core',
  theme            TEXT DEFAULT 'dark',
  is_muted         BOOLEAN DEFAULT false,
  is_voice_enabled BOOLEAN DEFAULT false,
  active_model     TEXT DEFAULT 'Groq / Gemini / DeepSeek',
  avatar_state     TEXT DEFAULT 'idle',
  orbit_open       BOOLEAN DEFAULT true,
  last_command     TEXT,
  state_data       JSONB DEFAULT '{}'::jsonb,
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial UI state row
INSERT INTO public.ui_state (id, active_subsystem, active_room, theme, is_muted, is_voice_enabled, active_model, avatar_state, orbit_open)
VALUES ('current', 'ai_core', 'ai_core', 'dark', false, false, 'Groq / Gemini / DeepSeek', 'idle', true)
ON CONFLICT (id) DO NOTHING;

-- ── SYSTEM & AUDIT LOGS ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.system_logs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source     TEXT NOT NULL,
  message    TEXT,
  text       TEXT,
  level      TEXT DEFAULT 'info',
  status     TEXT DEFAULT 'received',
  meta       JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── OMNI ROUTER REQUESTS ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.omni_router_requests (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prompt           TEXT NOT NULL,
  response         TEXT,
  provider         TEXT NOT NULL,
  model            TEXT NOT NULL,
  latency_ms       INTEGER,
  tokens_estimated INTEGER,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── COGNITIVE REQUESTS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cognitive_requests (
  id              TEXT PRIMARY KEY,
  request_type    TEXT,
  domain_type     TEXT,
  raw_prompt      TEXT,
  intents         JSONB DEFAULT '[]'::jsonb,
  entities        JSONB DEFAULT '[]'::jsonb,
  constraints     JSONB DEFAULT '[]'::jsonb,
  missing_context JSONB DEFAULT '[]'::jsonb,
  memory_bindings JSONB DEFAULT '[]'::jsonb,
  confidence      FLOAT8 DEFAULT 0.98,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── MISSIONS ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.missions (
  id         TEXT PRIMARY KEY,
  title      TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'queued',
  progress   INTEGER DEFAULT 0,
  objective  TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── AGENTS ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.agents (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  status         TEXT DEFAULT 'active',
  autonomy_level INTEGER DEFAULT 6,
  specialization TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ── MEMORY NODES ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.memory_nodes (
  id         TEXT PRIMARY KEY,
  title      TEXT NOT NULL,
  summary    TEXT,
  weight     FLOAT8 DEFAULT 1.0,
  tags       JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Canonical server memory. Existing installations already use this table.
CREATE TABLE IF NOT EXISTS public.microfixd_memory_records (
  id TEXT PRIMARY KEY,
  agent_id TEXT NOT NULL,
  run_id TEXT,
  kind TEXT NOT NULL CHECK (kind IN ('episodic','semantic','procedural','experience')),
  content TEXT NOT NULL,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  importance DOUBLE PRECISION NOT NULL CHECK (importance BETWEEN 0 AND 1),
  score DOUBLE PRECISION,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  tenant_id TEXT NOT NULL DEFAULT 'global',
  embedding VECTOR(1536),
  embedding_provider TEXT,
  embedding_model TEXT
);
ALTER TABLE public.microfixd_memory_records ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.microfixd_memory_records FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.microfixd_memory_records TO service_role;

-- ── AUTOMATION RULES ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.automation_rules (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  trigger    TEXT NOT NULL,
  action     TEXT NOT NULL,
  enabled    BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── MEMORY VECTOR STORE (pgvector) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.microfixd_memory (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content      TEXT NOT NULL,
  embedding    VECTOR(768),
  tags         TEXT[] DEFAULT '{}',
  organ        TEXT DEFAULT 'system',
  session_id   TEXT,
  importance   FLOAT DEFAULT 0.5,
  access_count INTEGER DEFAULT 0,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS memory_embedding_idx
  ON public.microfixd_memory USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

CREATE INDEX IF NOT EXISTS memory_tags_idx
  ON public.microfixd_memory USING GIN (tags);

-- ── EPISODE STORE ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.microfixd_episodes (
  episode_id        TEXT PRIMARY KEY,
  task              TEXT NOT NULL,
  success           BOOLEAN NOT NULL,
  cognitive_intent  TEXT,
  complexity        TEXT,
  elapsed_s         FLOAT,
  critic_score      FLOAT,
  eval_passed       BOOLEAN,
  steps             JSONB DEFAULT '{}',
  memory_hits       TEXT[] DEFAULT '{}',
  doctrine_warnings TEXT[] DEFAULT '{}',
  tags              TEXT[] DEFAULT '{}',
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS episodes_success_idx ON public.microfixd_episodes (success);
CREATE INDEX IF NOT EXISTS episodes_created_idx ON public.microfixd_episodes (created_at DESC);
CREATE INDEX IF NOT EXISTS episodes_intent_idx  ON public.microfixd_episodes (cognitive_intent);

-- ── HITL APPROVAL RECORDS ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.microfixd_hitl (
  hitl_id     TEXT PRIMARY KEY,
  session_id  TEXT,
  trigger     TEXT,
  artifact    JSONB NOT NULL,
  status      TEXT DEFAULT 'pending',
  notes       TEXT,
  decided_at  TIMESTAMPTZ,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── OVERWATCH ALERTS ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.microfixd_overwatch (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  level      TEXT NOT NULL,
  category   TEXT NOT NULL,
  message    TEXT NOT NULL,
  organ      TEXT,
  step       TEXT,
  resolved   BOOLEAN DEFAULT FALSE,
  episode_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── IDENTITY STORE (Immutable) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.microfixd_identity (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  locked     BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.microfixd_identity (key, value, locked) VALUES
  ('name',        'Microfixd',                          TRUE),
  ('level',       '7',                                  TRUE),
  ('model',       'gemini-2.5-flash',                   TRUE),
  ('constitution','active',                             TRUE),
  ('version',     '7.0.0',                              TRUE)
ON CONFLICT (key) DO NOTHING;

-- ── VECTOR COSINE SIMILARITY FUNCTION ────────────────────────────────────
CREATE OR REPLACE FUNCTION match_memories(
  query_embedding VECTOR(768),
  match_threshold FLOAT DEFAULT 0.7,
  match_count     INT   DEFAULT 5
)
RETURNS TABLE (
  id UUID, content TEXT, tags TEXT[], organ TEXT,
  importance FLOAT, similarity FLOAT
)
LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.id, m.content, m.tags, m.organ, m.importance,
    1 - (m.embedding <=> query_embedding) AS similarity
  FROM public.microfixd_memory m
  WHERE 1 - (m.embedding <=> query_embedding) > match_threshold
  ORDER BY m.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ── ROW-LEVEL SECURITY POLICIES (Allow App Operations) ────────────────────
-- Enables RLS on all tables and allows full read/write for both anonymous & authenticated clients
DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'ui_state', 'system_logs', 'omni_router_requests', 'cognitive_requests',
    'missions', 'agents', 'memory_nodes', 'automation_rules',
    'microfixd_memory', 'microfixd_episodes', 'microfixd_hitl',
    'microfixd_overwatch', 'microfixd_identity'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', 'Allow full access to ' || tbl, tbl);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);', 'Allow full access to ' || tbl, tbl);
  END LOOP;
END $$;
